name: GH Actions
on:
  issues:
    types: [opened]
  jobs:
    auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign PR'
        uses: pozile/auto-assign-issues@v1
        with:
          assignees:  deraowl
          repo-token: ${{ secrets_GITHUB.TOKEN  }}
